<?php

/**
 * @file
 * Main module file for HomeCoop
 * 
 * Local Consumer Cooperatives Web Ordering System
 */

/**
 * Implement hook_help().
 */
function homecoop_help($path, $args) {
  if ($path == 'admin/help#homecoop') {
    return t('Local Consumer Cooperatives Web Ordering System');
  }
}

/**
 * Implements hook_menu()
 */
function homecoop_menu() {
  $items = array();
    
  $items["hcfront"] = array(
    'page callback' => 'homecoop_page_front',
    'access callback' => 'homecoop_public_access',
    'file' => 'pages/home.inc',
  );
  
  $items["hclogin"] = array(
    'page callback' => 'homecoop_page_login',
    'access callback' => 'homecoop_public_access',
    'file' => 'pages/login.inc',
  );

  return $items;
}

/*
 * Implements hook_views_api()
 */
function homecoop_views_api() {
  $vpath = drupal_get_path('module', 'homecoop') . '/views';
  return array(
    'api' => 3,
    'path' => $vpath,
    'template path' => $vpath,
  );
}

/**
 * Implements hook_permission()
 */
function homecoop_permission() {
  return array(
  );
}

/*
 * Implements hook_cron()
 */
function homecoop_cron() {
}

function homecoop_public_access() {
  return TRUE;
}

function homecoop_include_app_file($path) {
  global $language;
  
  require_once(DRUPAL_ROOT . '/' . drupal_get_path('module', 'homecoop') . "/app/$language->language/$path.php");
}

function homecoop_add_js_file($JsScriptFile) {
  $path = drupal_get_path('module', 'homecoop');
  $options = array(
     'group' => JS_LIBRARY,
     'cache' => FALSE,
     'preprocess' => FALSE,
     'defer' => TRUE,
  );
  drupal_add_js($path . '/js/' . $JsScriptFile);
}

function homecoop_any_page() {
  homecoop_include_app_file('settings');
  
  global $g_oMemberSession;
  
  $hcsettings = array(
    'IsCoordUser' => (isset($g_oMemberSession) && !$g_oMemberSession->IsOnlyMember),
   );
  
  drupal_add_js(array('homecoop' => $hcsettings), 'setting');
}

function homecoop_authenticated_page() {
  homecoop_include_app_file('settings');
  homecoop_include_app_file('authenticate');
  
  global $g_oMemberSession;
  
  $hcsettings = array(
    'IsCoordUser' => (isset($g_oMemberSession) && !$g_oMemberSession->IsOnlyMember),
   );
  
  drupal_add_js(array('homecoop' => $hcsettings), 'setting');
  
  homecoop_add_js_file('authenticated.js');
}

function homecoop_check_if_authenticated() {
  global $g_oMemberSession;
  if (isset($g_oMemberSession)) {
    return $g_oMemberSession->IsLoggedIn;
  }
  else {
    $g_oMemberSession = new UserSession();
    return $g_oMemberSession->Authenticate();
  }
}

/**
* Implements hook_block_info().
*/
function homecoop_block_info() {
  $blocks = array();
  
  $blocks['homecoop_header'] = array(
    'info' => t('HomeCoop header'),
    'cache' => DRUPAL_CACHE_GLOBAL, //since this is a new form, we can cache it
  );
  
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function homecoop_block_view($block_name = '') {
  switch ($block_name) {
    case 'homecoop_header':
      require_once(DRUPAL_ROOT . '/' . drupal_get_path('module', 'homecoop') . '/blocks/header.inc');
      $block = array(
        'subject' => t('Header'),
        'content' => homecoop_header_block(),
      );
      return $block;
  }
}