<?php

/**
 * @file
 * Main module file for HomeCoop
 * 
 * Local Consumer Cooperatives Web Ordering System
 */

/**
 * Implement hook_help().
 */
function homecoop_help($path, $args) {
  if ($path == 'admin/help#homecoop') {
    return t('Local Consumer Cooperatives Web Ordering System');
  }
}

/**
 * Implements hook_menu()
 */
function homecoop_menu() {
  return array(
    'hcfront' => array(
      'page callback' => 'homecoop_page_front',
      'access callback' => 'homecoop_public_access',
      'file' => 'pages/home.inc',
    ),
    'hclogin' => array(
      'page callback' => 'homecoop_page_login',
      'access callback' => 'homecoop_public_access',
      'file' => 'pages/login.inc',
    ),
    'hcorder' => array(
      'page callback' => 'homecoop_page_order',
      'access callback' => 'homecoop_public_access',
      'file' => 'pages/order.inc',
    ),
    'hcaccessdenied' => array(
      'page callback' => 'homecoop_page_accessdenied',
      'access callback' => 'homecoop_public_access',
      'file' => 'pages/accessdenied.inc',
    ),
  );
}

/*
 * Implements hook_views_api()
 */
function homecoop_views_api() {
  $vpath = drupal_get_path('module', 'homecoop') . '/views';
  return array(
    'api' => 3,
    'path' => $vpath,
    'template path' => $vpath,
  );
}

/**
 * Implements hook_permission()
 */
function homecoop_permission() {
  return array(
  );
}

/*
 * Implements hook_cron()
 */
function homecoop_cron() {
}

function homecoop_public_access() {
  return TRUE;
}

function homecoop_include_app_file($path) {
  global $language;
  
  require_once(DRUPAL_ROOT . '/' . drupal_get_path('module', 'homecoop') . "/app/$language->language/$path.php");
}

function homecoop_add_js_file($JsScriptFile) {
  $path = drupal_get_path('module', 'homecoop');
  $options = array(
     'group' => JS_LIBRARY,
     'cache' => FALSE,
     'preprocess' => FALSE,
     'defer' => TRUE,
  );
  drupal_add_js($path . '/js/' . $JsScriptFile);
}

function homecoop_any_page() {
  homecoop_include_app_file('settings');
  
  global $g_oMemberSession;
  
  $hcsettings = array(
    'IsCoordUser' => (isset($g_oMemberSession) && !$g_oMemberSession->IsOnlyMember),
   );
  
  drupal_add_js(array('homecoop' => $hcsettings), 'setting');
}

function homecoop_authenticated_page() {
  //drupal_get_messages(); //clear all previous errors from the queue
  homecoop_include_app_file('settings');
  homecoop_include_app_file('authenticate');
  
  global $g_oMemberSession;
  
  $hcsettings = array(
    'IsCoordUser' => (isset($g_oMemberSession) && !$g_oMemberSession->IsOnlyMember),
   );
  
  drupal_add_js(array('homecoop' => $hcsettings), 'setting');
  
  homecoop_add_js_file('authenticated.js');
}

function homecoop_check_if_authenticated() {
  global $g_oMemberSession;
  if (isset($g_oMemberSession)) {
    return $g_oMemberSession->IsLoggedIn;
  }
  else {
    $g_oMemberSession = new UserSession();
    return $g_oMemberSession->Authenticate();
  }
}

/**
* Implements hook_block_info().
*/
function homecoop_block_info() {
  return array(
    'homecoop_header' => array(
      'info' => t('HomeCoop header'),
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
  );
}

/**
* Implements hook_block_view().
*/
function homecoop_block_view($block_name = '') {
  switch ($block_name) {
    case 'homecoop_header':
      require_once(DRUPAL_ROOT . '/' . drupal_get_path('module', 'homecoop') . '/blocks/header.inc');
      $block = array(
        'subject' => t('Header'),
        'content' => homecoop_header_block(),
      );
      return $block;
  }
}

function homecoop_LoadSpecificFacet(&$oFacet, &$aFacet, &$aFacetIDs, &$nFacetRemoved, $sIDField)
{
  $aFacet = array();
  $aFacetIDs = array();
  $nFacetRemoved = 0;
  
  $arrTemp = $oFacet->GetTableForFacet();
  
  //add producer id as key
  foreach ($arrTemp as $oTemp)
  {
    $aFacet[$oTemp[$sIDField]] = $oTemp;
    if (!$oTemp['bDisabled'] && !$oTemp['bBlocked'])
    {
      if ($oTemp['bRemoved'])
        $nFacetRemoved++;
      else
        $aFacetIDs[$oTemp[$sIDField]] = $oTemp[$sIDField];
    }
  }
}

function homecoop_prepare_pickup_facet() {
  //prepare facet data
  $GLOBALS['g_oMemberPickupLocations'] = NULL;
  $GLOBALS['g_aMemberPickupLocations'] = NULL;
  $GLOBALS['g_aMemberPickupLocationIDs'] = NULL;
  $GLOBALS['g_nMemberPickupLocationsRemoved'] = 0;

  global $g_oMemberPickupLocations, $g_aMemberPickupLocations, $g_aMemberPickupLocationIDs, $g_nMemberPickupLocationsRemoved;
    
  $g_oMemberPickupLocations = new MemberPickupLocations();
  homecoop_LoadSpecificFacet($g_oMemberPickupLocations, $g_aMemberPickupLocations, $g_aMemberPickupLocationIDs, $g_nMemberPickupLocationsRemoved,
      'PickupLocationKeyID');
}

function homecoop_prepare_producer_facet() {
  $GLOBALS['g_oMemberProducers'] = NULL;
  $GLOBALS['g_aMemberProducers'] = NULL;
  $GLOBALS['g_aMemberProducerIDs'] = NULL;
  $GLOBALS['g_nMemberProducersRemoved'] = 0;
  
  global $g_oMemberProducers, $g_aMemberProducers, $g_aMemberProducerIDs, $g_nMemberProducersRemoved;
  
  $g_oMemberProducers = new MemberProducers();
  homecoop_LoadSpecificFacet($g_oMemberProducers, $g_aMemberProducers, $g_aMemberProducerIDs, $g_nMemberProducersRemoved,
      'ProducerKeyID');
}

function homecoop_tab_cooporder(&$oFormExtraData) {
  if (!isset($oFormExtraData['cooptab']) || empty($oFormExtraData['cooptab']) || !$oFormExtraData['coopordertabaccess']) {
    return array();
  }
  
  $oTabInfo = $oFormExtraData['cooptab'];
  $arrContent = array(
    '#prefix' => '<table cellpadding="0" cellspacing="0" border="0" width="100%" >',
    '#suffix' => '</table>',
  );
  
  if ($oTabInfo->ID > 0) {
    $arrSums = array(
      '#prefix' => '<tr><td align="center"><table cellpadding="2" cellspacing="0" border="0" ><tr>',
      '#suffix' => '</tr></table></td></tr>',
    );

    if ($oFormExtraData['hassumspermission']) {
      $arrSums['totalcoop'] = array(
        'totalcooplabel' => array(
          '#prefix' => '<td class="headmainlabel">',
          '#markup' => t('Total Coop:&nbsp;'),
          '#suffix' => '</td>',
        ),
         'totalcoopdata' => array(
          '#prefix' => '<td class="headmaindata">',
          '#markup' => $oTabInfo->CoopTotal,
          '#suffix' => '</td>',
        ),
      );
    }
    
    $arrSums['sep1'] = array(
      '#markup' => '<td>&nbsp;&nbsp;</td>',
    );

    if ($oTabInfo->Capacity != NULL) {
      $arrSums['capacity'] = array(
        '#prefix' => '<td class="headmaindata">',
        '#markup' => t('@percent&nbsp;Full', array('@percent' => $oTabInfo->Capacity)),
        '#suffix' => '</td>',
      );
    }
    
    $arrSums['sep2'] = array(
      '#markup' => '<td>&nbsp;&nbsp;</td>',
    );
    
    if ($oTabInfo->StatusObj != NULL) {
      $arrSums['status'] = array(
        '#prefix' => '<td nowrap class="headmaindata">',
        '#markup' => $oTabInfo->StatusObj->StatusName,
        '#suffix' => '</td>',
      );
    }
    $arrContent['sums'] = $arrSums;
  }
  
  //Main TAB
  $arrContent['maintab'] = array(
    '#prefix' => '<tr><td><ul class="tabrow">',
    '#suffix' => '</ul></td></tr>',
  );
  
  $sCoopOrderTabSelected = '';
  $sPickupLocationTabSelected = '';
  $sOrderTabSelected = '';
  $sCurrentMainTab = '';
  $sCurrentMainTabItem = '';
  
  $bHasOrder = $oFormExtraData['hasorder'];
  $bHasPickupLocation = (isset($oFormExtraData['pltab']) && !empty($oFormExtraData['pltab']) &&  $oFormExtraData['pltab']->PickupLocationID > 0 
      && $oFormExtraData['pltab']->IsExistingRecord);

  if ($bHasOrder) {
    $sOrderTabSelected = 'class="selected"';
    $sCurrentMainTab = 'tabOrder';
  }
  elseif ($bHasPickupLocation) {
    $sPickupLocationTabSelected = 'class="selected"';
    $sCurrentMainTab = 'tabPickupLocation';
  }
  else {
    $sCoopOrderTabSelected = 'class="selected"';
    $sCurrentMainTab = 'tabCoopOrder';
  }
  
  $arrContent['hidCurrentMainTab'] = array('#type' => 'hidden', '#default_value' => $sCurrentMainTab, 
    '#attributes' => array('id' => 'hidCurrentMainTab'));

  $arrContent['maintab']['coopordertabanchor'] = array(
    '#prefix' => '<li id="tabCoopOrderItem" onclick="javascript:ToggleTabDisplay(\'tabCoopOrder\');" ' . $sCoopOrderTabSelected  . ' title="' .
      t('Cooperative Order') . '">',
    '#markup' => $oTabInfo->CoopOrderTitle,
    '#suffix' => '</li>',
  );

  if ($bHasPickupLocation) {
    $arrContent['maintab']['pltabanchor'] = array(
      '#prefix' => '<li id="tabPickupLocationItem" onclick="javascript:ToggleTabDisplay(\'tabPickupLocation\');"  ' . $sPickupLocationTabSelected . 
      ' title="' . t('Location Name') . '">',
      '#markup' => $oFormExtraData['pltab']->MainTabName,
      '#suffix' => '</li>',
    );
  }

  if ($bHasOrder) {
    $arrContent['maintab']['ordertabanchor'] = array(
      '#prefix' => '<li id="tabOrderItem" onclick="javascript:ToggleTabDisplay(\'tabOrder\');"  ' . $sOrderTabSelected . '>',
      '#markup' => $oFormExtraData['ordertab']->MainTabName,
      '#suffix' => '</li>',
    );
  }
  
  $arrContent['coopordertab'] = array(
    '#prefix' => '<tr id="tabCoopOrder" ' . ($bHasOrder || $bHasPickupLocation ? ' style="display: none;" >' : '>') .
      '<td><table cellpadding="0" cellspacing="0" border="0" width="100%" ><tr><td><ul class="tabrow subtabrow">',
    '#suffix' => '</ul></td></tr></table></td></tr>',
  );
  
  $arrContent['coopordertab']['headeranchor'] = homecoop_tab_cooporder_write_element($oTabInfo, t('Header'), 
      url('hccoord/cooporder', 
          array('query' => 
                  array('id' => $oTabInfo->ID),
          )), $oTabInfo->Page == CoopOrderTabInfo::PAGE_ENTRY);

  if ($oTabInfo->ID > 0) { //existing record
    $arrContent['coopordertab']['planchor'] = homecoop_tab_cooporder_write_element($oTabInfo, t('Pickup Locations'),
        url('hccoord/copickuplocs', 
          array('query' => 
                  array('id' => $oTabInfo->ID),
          )), $oTabInfo->Page == CoopOrderTabInfo::PAGE_PICKUP);
    
    if ($oFormExtraData['hasproducerspermission']) {
      $arrContent['coopordertab']['producersanchor'] = homecoop_tab_cooporder_write_element($oTabInfo, t('Producers'),
          url('hccoord/coproducers', 
          array('query' => 
                  array('id' => $oTabInfo->ID),
          )), $oTabInfo->Page == CoopOrderTabInfo::PAGE_PRODUCERS);
    }
    
    if ($oFormExtraData['hasproductspermission']) {
      $arrContent['coopordertab']['productssanchor'] = homecoop_tab_cooporder_write_element($oTabInfo, t('Products'),
          url('hccoord/coproducts', 
          array('query' => 
                  array('id' => $oTabInfo->ID),
          )), $oTabInfo->Page == CoopOrderTabInfo::PAGE_PRODUCTS);
    }
    
    if ($oFormExtraData['hasorderspermission']) {
      $arrContent['coopordertab']['orderssanchor'] = homecoop_tab_cooporder_write_element($oTabInfo, t('Member Orders'),
          url('hccoord/orders', 
          array('query' => 
                  array('id' => $oTabInfo->ID),
          )), $oTabInfo->Page == CoopOrderTabInfo::PAGE_ORDERS);
    }
    
    $arrContent['coopordertab']['exportanchor'] = homecoop_tab_cooporder_write_element($oTabInfo, t('Export Data'),
        url('hccoord/cooporderexport', 
          array('query' => 
                  array('id' => $oTabInfo->ID),
          )), $oTabInfo->Page == CoopOrderTabInfo::PAGE_EXPORT_DATA);
    
    if ($oFormExtraData['hascopypermission']) {
      $arrContent['coopordertab']['copyanchor'] = homecoop_tab_cooporder_write_element($oTabInfo, t('Copy'),
          url('hccoord/coopordercopy', 
          array('query' => 
                  array('id' => $oTabInfo->ID),
          )), FALSE);
    }
    
    if ($oFormExtraData['hascoordsetpermission']) {
      $query = array('rid' => $oTabInfo->ID,
        'pa' => Consts::PERMISSION_AREA_COOP_ORDERS,
        );

      if ($oTabInfo->CoordinatingGroupID > 0) {
        $query['id'] = $oTabInfo->CoordinatingGroupID;
      }
    
      $arrContent['coopordertab']['coordsetanchor'] = homecoop_tab_cooporder_write_element($oTabInfo, t('Coordination'),
        url('hccoord/coordinate', $query), FALSE);
    }
  }
  
  return $arrContent;
}

function homecoop_tab_copickuploc(&$oFormExtraData) {
   if (!isset($oFormExtraData['pltab']) || empty($oFormExtraData['pltab']) ||
       $oFormExtraData['pltab']->PickupLocationID == 0 || !$oFormExtraData['pltab']->IsExistingRecord
       || !$oFormExtraData['coopordertabaccess'] || !$oFormExtraData['pltabaccess']
       ) {
    return array();
  }
  
  $oPLTabInfo = $oFormExtraData['pltab'];
  
  $arrContent = array(
    'tabs' => array(
      '#prefix' => '<table id="tabPickupLocation" ' . ($oFormExtraData['hasorder']? ' style="display: none;" ' : '') . 
        ' cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td><ul class="tabrow subtabrow" >',
      '#suffix' => '</ul></td></tr></table>',
      'plheadertab' => homecoop_tab_cooporder_pickuploc_write_element($oPLTabInfo, $oPLTabInfo->MainTabName,
          url('hccoord/copickuploc', array(
            'query' => array(
              'coid' => $oPLTabInfo->CoopOrderID,
              'plid' => $oPLTabInfo->PickupLocationID,
            )
          )), $oPLTabInfo->Page == CoopOrderPickupLocationTabInfo::PAGE_PICKUP_LOCATION),
    ),
  );
  
  if ($oFormExtraData['hasplproducerpermission']) {
    $arrContent['tabs']['plproducerstab'] = homecoop_tab_cooporder_pickuploc_write_element($oPLTabInfo, t('Producers'),
          url('hccoord/copickuplocproducers', array(
            'query' => array(
              'coid' => $oPLTabInfo->CoopOrderID,
              'plid' => $oPLTabInfo->PickupLocationID,
            )
          )), $oPLTabInfo->Page == CoopOrderPickupLocationTabInfo::PAGE_PRODUCERS);
  }
  
  if ($oFormExtraData['hasplproductspermission']) {
    $arrContent['tabs']['plproductstab'] = homecoop_tab_cooporder_pickuploc_write_element($oPLTabInfo, t('Products'),
          url('hccoord/copickuplocproducts', array(
            'query' => array(
              'coid' => $oPLTabInfo->CoopOrderID,
              'plid' => $oPLTabInfo->PickupLocationID,
            )
          )), $oPLTabInfo->Page == CoopOrderPickupLocationTabInfo::PAGE_PRODUCTS);
  }
  
  if ($oFormExtraData['hasplorderspermission']) {
    $arrContent['tabs']['plorderstab'] = homecoop_tab_cooporder_pickuploc_write_element($oPLTabInfo, t('Orders'),
          url('hccoord/copickuplocorders', array(
            'query' => array(
              'coid' => $oPLTabInfo->CoopOrderID,
              'plid' => $oPLTabInfo->PickupLocationID,
            )
          )), $oPLTabInfo->Page == CoopOrderPickupLocationTabInfo::PAGE_ORDERS);
  }
  
  return $arrContent;
}

function homecoop_tab_order(&$oFormExtraData) {
   if (!isset($oFormExtraData['ordertab']) || empty($oFormExtraData['ordertab'])) {
    return array();
  }
  
  $oOrderTabInfo = $oFormExtraData['ordertab'];
  
  $arrContent = array(
    'tabs' => array(
      '#prefix' => '<table id="tabOrder" cellpadding="0" cellspacing="0" border="0" width="100%"><tr><td><ul class="tabrow subtabrow">',
      '#suffix' => '</ul></td></tr></table>',
    ),
  );
  
  $arrContent['tabs']['orderheadertab'] = homecoop_tab_order_write_element($oOrderTabInfo, t('Header'),
      url('hcorder', 
          array('query' => 
                  array('id' => $oOrderTabInfo->ID),
          )), $oOrderTabInfo->Page == OrderTabInfo::PAGE_ENTRY);
  
  if ($oOrderTabInfo->ID > 0) {
    $arrContent['tabs']['orderitemstab'] = homecoop_tab_order_write_element($oOrderTabInfo, t('Order Items'),
        url('hcorderitems', 
          array('query' => 
                  array('id' => $oOrderTabInfo->ID),
          )), $oOrderTabInfo->Page == OrderTabInfo::PAGE_ITEMS);
  }
  
  $nCoopTotal = $oOrderTabInfo->CoopTotal;
  $sOrderSumClass = '';
  if ($oOrderTabInfo->StatusObj->Status == ActiveCoopOrderStatus::Open) {
    $sOrderSumClass = " opensum";
  }
  else {
    $sOrderSumClass = " closedsum";
  }
  
  $arrContent['ordersummary'] = array(
    '#prefix' => '<div class="ordersummary' . $sOrderSumClass . '">',
    '#suffix' => '</div>',
  );
  
  if ($oOrderTabInfo->OrderCoopFee != NULL && $oOrderTabInfo->OrderCoopFee != 0) {
    $nCoopTotal += $oOrderTabInfo->OrderCoopFee;
    $arrContent['ordersummary']['totalproducts'] = array(
      '#prefix' => '<div class="headlabel" >' . t('Total Products‏:‏‎&nbsp;'),
      '#markup' => $oOrderTabInfo->CoopTotal,
      '#suffix' => '</div>',
    );
    $arrContent['ordersummary']['ordercoopfee'] = array(
      '#prefix' => '<div class="headlabel" >' . t('Coop Fee‏‏:‏‎&nbsp;'),
      '#markup' => $oOrderTabInfo->OrderCoopFee,
      '#suffix' => '</div>',
    );
  }
  
  $arrContent['ordersummary']['totalamount'] = array(
    '#prefix' => '<div class="headlabel" >' . t('Total Amount‏:‏‎&nbsp;'),
    '#markup' => $nCoopTotal,
    '#suffix' => '</div>',
  );
  
  if ($oOrderTabInfo->StatusObj->StatusName != NULL) {
    $arrContent['ordersummary']['status'] = array(
      '#prefix' => '<div class="headlabel" >',
      '#markup' => $oOrderTabInfo->StatusObj->StatusName,
      '#suffix' => '</div>',
    );
  }
  
  if ($oOrderTabInfo->Capacity != NULL) {
    $arrContent['ordersummary']['capacity'] = array(
      '#prefix' => '<div class="headlabel" >',
      '#markup' => t('@percent&nbsp;Full', array('@percent' => $oOrderTabInfo->Capacity)),
      '#suffix' => '</div>',
    );
  }
  
  return $arrContent;
}

function homecoop_tab_cooporder_write_element($oTabInfo, $sText, $sLink, $bIsOnPage)
{
  $arrContent = array();
  if ($sText == '') {
      return $arrContent;
  }
  
  $arrContent['#prefix'] = '<li';
  $arrContent['#suffix'] = '</li>';
  
  if ($bIsOnPage) {
    $arrContent['#prefix'] .= ' class="selected" ';
  }
   
  if (!$bIsOnPage || $oTabInfo->IsSubPage) {
    $arrContent['#prefix'] .=  ' onclick="javascript:location.href = \'' . $sLink . '\';"';
  }
  $arrContent['#prefix'] .= '>';
  
  $arrContent['#markup'] = $sText;
  return $arrContent;
}

function homecoop_tab_order_write_element($oOrderTabInfo, $sText, $sLink, $bIsOnPage)
{      
  $arrContent = array(
    '#prefix' => '<li',
    '#markup' => ' >' . $sText,
    '#suffix' => '</li>',
  );
  
  if ($bIsOnPage) {
    $arrContent['#prefix'] .= ' class="selected" ';
  }
  elseif ($oOrderTabInfo->ID > 0) {
    $arrContent['#prefix'] .= ' onclick="javascript:location.href = \'' . $sLink . '\';"'; 
  }
  
  return $arrContent;
} 

function homecoop_tab_cooporder_pickuploc_write_element($oPLTabInfo, $sText, $sLink, $bIsOnPage)
{    
  $arrContent = array(
    '#prefix' => '<li',
    '#markup' => ' >' . $sText,
    '#suffix' => '</li>',
  );
  
  if ($bIsOnPage) {
    $arrContent['#prefix'] .= ' class="selected" ';
  }
  
  if (!$bIsOnPage || $oPLTabInfo->IsSubPage) {
    $arrContent['#prefix'] .= ' onclick="javascript:location.href = \'' . $sLink . '\';"';
  }
  
  return $arrContent;
}

function homecoop_get_tabs_info($oTabInfo, $oOrderTabInfo, $oPLTabInfo, $bHasCoordPermission) {
  $arrData = array(
    'ordertab' => $oOrderTabInfo,
    'hasorder' => (isset($oOrderTabInfo) && !empty($oOrderTabInfo)),
    'pltab' => $oPLTabInfo,
    'cooptab' => $oTabInfo,
   );
  
  if ($oTabInfo != NULL) {
    $arrData += array(
      'coopordertabaccess' => $oTabInfo->CheckAccess(),
      'hassumspermission' => $oTabInfo->CheckCoopOrderSumsPermission(),
      'hasproducerspermission' => $oTabInfo->CheckCoopOrderProducersPermission(),
      'hasproductspermission' => $oTabInfo->CheckCoopOrderProductsPermission(),
      'hasorderspermission' => $oTabInfo->CheckCoopOrderOrdersPermission(),
      'hascopypermission' => $bHasCoordPermission && $oTabInfo->CheckCoopOrderCopyPermission(),
      'hascoordsetpermission' => $oTabInfo->CheckCoopOrderSetCoordPermission(),
      );
  }
  
  if ($oPLTabInfo != NULL) {
    $arrData += array(
      'pltabaccess' => $oPLTabInfo->CheckAccess(),
      'hasplproducerpermission' => $oPLTabInfo->CheckProducersPermission(),
      'hasplproductspermission' => $oPLTabInfo->CheckProductsPermission(),
      'hasplorderspermission' => $oPLTabInfo->CheckOrdersPermission(),
      );
  }
  
  return $arrData;
}